version: '3'
services:
  database:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local