### Pobranie repo
POST http://127.0.0.1:8000/testproject_01/git
Content-Type: application/json

{
  "repositoryUrl": "https://github.com/baranosiu/testproject.git",
  "branch": "master"
}

### Update (git pull)
PUT http://127.0.0.1:8000/testproject_01/git

### Wystartowanie zadania (jeśli trzeba, to pobranie/budowanie obrazów dla Dockera)
POST http://127.0.0.1:8000/testproject_01

"TASK_COMMAND_START"

### Pobranie logów
POST http://127.0.0.1:8000/testproject_01

"TASK_COMMAND_LOG"

### Zatrzymanie zadania
POST http://127.0.0.1:8000/testproject_01

"TASK_COMMAND_STOP"

### Status zadania
POST http://127.0.0.1:8000/testproject_01

"TASK_COMMAND_STATUS"

### Czyszczenie voluminów i obrazów zadania (pliki z repo i wynikowe zostają)
POST http://127.0.0.1:8000/testproject_01

"TASK_COMMAND_CLEANUP"

### Usuwanie workspace taska
POST http://127.0.0.1:8000/testproject_01

"TASK_COMMAND_DELETE"

### Przykład pobierania pliku wyniku
GET http://127.0.0.1:8000/testproject_01/ftp/out/wynik.txt

### Przykład wysłania pliku
POST http://127.0.0.1:8000/testproject_01/ftp/out/test.txt
Content-Type: application/octet-stream

Jakaś tam zawartość pliku testowego.
### EOF