### Pobranie repo
POST http://127.0.0.1:8000/testproject_01/git
Content-Type: application/json

{
  "repositoryUrl": "https://github.com/baranosiu/testproject.git",
  "branch": "master"
}

### Update (git pull)
PUT http://127.0.0.1:8000/testproject_01/git

### Wystartowanie Dockera
POST http://127.0.0.1:8000/testproject_01

"TASK_COMMAND_START"

### Pobranie logów
POST http://127.0.0.1:8000/testproject_01

"TASK_COMMAND_LOG"

### Wyłączenie Dockera
POST http://127.0.0.1:8000/testproject_01

"TASK_COMMAND_STOP"

### Czyszczenie voluminów i obrazów Dockera (pliki z repo i wynikowe zostają)
POST http://127.0.0.1:8000/testproject_01

"TASK_COMMAND_CLEANUP"

### Przykład pobierania pliku wyniku
GET http://127.0.0.1:8000/testproject_01/ftp/out/wynik.txt

### Przykład wysłania pliku
POST http://127.0.0.1:8000/testproject_01/ftp/out/test.txt
Content-Type: application/octet-stream

Jakaś tam zawartość pliku testowego.
### EOF