### Utworzenie docker-compose.yml
POST http://127.0.0.1:8000/test_03/ftp/docker-compose.yml
Content-Type: application/octet-stream

version: "3"
services:
  linux:
    image: alpine
    command: "date"

### EOF

### Uruchomienie zadania
POST http://127.0.0.1:8000/test_03

"TASK_COMMAND_START"

### Pobranie logów
POST http://127.0.0.1:8000/test_03

"TASK_COMMAND_LOG"

### Zatrzymanie zadania
POST http://127.0.0.1:8000/test_03

"TASK_COMMAND_STOP"

### Status zadania
POST http://127.0.0.1:8000/test_03

"TASK_COMMAND_STATUS"

### Czyszczenie voluminów i obrazów zadania (pliki z repo i wynikowe zostają)
POST http://127.0.0.1:8000/test_03

"TASK_COMMAND_CLEANUP"

### Usuwanie workspace taska
POST http://127.0.0.1:8000/test_03

"TASK_COMMAND_DELETE"
